CREATE TABLE todolists(
    id BIGSERIAL PRIMARY KEY,
    title TEXT NOT NULL CHECK ( LENGTH(title) > 0 AND LENGTH(title) <= 128 ),
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
)